[workspace]
members = [
    "portfolio",
    "stablecoin",
    "risklock",
    "loans_pool",
    "governance",
    "zk_verifier",
    "batch_executor",
    "mev_guard", "vc_registry", "rwa_tokenizer", "dao_governance", "recurring_payments", "insurance_pool",
]
resolver = "2"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
